apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-frontend
  labels:
    app: greetings
    type: frontend
spec:
  template:
    metadata:
      name: greetings-frontend
      labels:
        app: greetings
        type: frontend
    spec:
      containers:
        - name: greetings-frontend
          image: dockerdemo786/greetings-frontend:1.0.0
          ports:
            - containerPort: 80 # Port on which the app is running inside the container
  selector:
    matchLabels:
      app: greetings
      type: frontend
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: greetings-frontend
  labels:
    app: greetings
    type: frontend
spec:
  type: NodePort
  ports:
    - port: 80 
      targetPort: 80 # Port inside the container (where Nginx listens)
      protocol: TCP
  selector: # Selector to match the pods
    app: greetings
    type: frontend